packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@prisma/engines': true
  bcrypt: set this to true or false
  prisma: true

onlyBuiltDependencies:
  "@prisma/engines": true
  prisma: true
  esbuild: true
